### ISSUE TITLE
Create the Migration in Progress Cards

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#10]
This issue will handle creating the UI components for the Migration in Progress Cards.

Subject to UX approval: 
These will be using the Utilization Bar Card pattern referenced here:
http://www.patternfly.org/pattern-library/cards/utilization-bar-card/

There is also a PF React issue here for Base Card:
https://github.com/patternfly/patternfly-react/issues/192

The Utilization Bar can be contributed to PF React as well (so I think we should start here for this issue):
https://github.com/patternfly/patternfly-react/issues/193

**Comment by serenamarie125** [comment]
<img width="571" alt="screen shot 2018-02-03 at 12 34 57 am" src="https://user-images.githubusercontent.com/12504403/35763448-84089eae-087a-11e8-9c99-6e6d12709a96.png">
<img width="576" alt="screen shot 2018-02-03 at 12 34 40 am" src="https://user-images.githubusercontent.com/12504403/35763449-841b0292-087a-11e8-8b06-36755546c51f.png">

**Comment by priley86** [comment]
High fidelity design is here:
![v2v overview page-populated 2 2x](https://user-images.githubusercontent.com/4237045/36450584-6a81cc68-165c-11e8-9268-0f40ca502780.png)

**Comment by mturley** [comment]
Sounds like @jeff-phillips-18 might be the one doing this.  Relevant API examples: https://gist.github.com/bzwei/3213174ee5efb4e377d789df8394cf2b
