### ISSUE TITLE
Show target cluster names as well as source cluster names in the dropdowns on the Datastores and Networks pages of the mapping wizard

### ISSUE THREAD

**Issue by mturley** [priley86/miq_v2v_ui_plugin#103]
From @vconzola:

> Show target cluster names as well as source cluster names in the dropdowns on the Datastores and Networks pages of the mapping wizard. For example, show "Raleigh (rehvh1-local)" instead of just "Raleigh". This will tie the dropdown to the tree view below when mappings are done.

**Comment by serenamarie125** [comment]
Making this a p1, but worried that this may affect the layout of screens ... make sure we get a quick UX review on this before PR is merged please @vconzola FYI

**Comment by michaelkro** [comment]
Handled by https://github.com/priley86/miq_v2v_ui_plugin/pull/113

**Comment by mturley** [comment]
Closed by #113
