### ISSUE TITLE
Show source datastores sizes and target datastores available space in the lists

### ISSUE THREAD

**Issue by mturley** [priley86/miq_v2v_ui_plugin#104]
From @vconzola: 

> Show source datastores sizes and target datastores available space in the lists. List headings should be "Source Datastores (size)" and "Target Datastores (available)". A datastore would look like "VMware DS1 (1234 GB)" in the list.

**Comment by michaelkro** [comment]
https://github.com/priley86/miq_v2v_ui_plugin/pull/108
