### ISSUE TITLE
Add ability to remove mappings at the source datastore/network level

### ISSUE THREAD

**Issue by mturley** [priley86/miq_v2v_ui_plugin#105]
From @vconzola:

> Add ability to remove mappings at the source datastore/network level. I know this goes against what I told you before Mike Ro, but after playing with the UI, this would be useful.

@michaelkro, sounds like this one might fall on stuff you're already working on?

**Comment by mturley** [comment]
@michaelkro mentioned on Slack that he had this one in progress and that it may take a bit longer.

**Comment by priley86** [comment]
closed by #123
