### ISSUE TITLE
Change the infra mapping dropdown on step 1 of the plans wizard so that it actually drops down instead of flying up

### ISSUE THREAD

**Issue by mturley** [priley86/miq_v2v_ui_plugin#107]
From @vconzola:

> Change the infra mapping dropdown on step 1 of the plans wizard so that it actually drops down instead of flying up. @patrick says this is the default browser behavior, but it's just weird.

Not sure if you were already looking at this, @priley86 .

**Comment by priley86** [comment]
The "General Step" dropdowns are currently just using native browser `select` elements. This appears to be a Foreman convention as well. Should we change the dropdowns to PF React dropdowns instead of native selects? This is cosmetic...

<img width="899" alt="screen shot 2018-03-02 at 3 06 13 pm" src="https://user-images.githubusercontent.com/4237045/36919602-e5399752-1e2b-11e8-8981-c5a4fff59fbe.png">
<img width="899" alt="screen shot 2018-03-02 at 3 06 20 pm" src="https://user-images.githubusercontent.com/4237045/36919607-e7923d56-1e2b-11e8-99ef-0dc0a53accae.png">


<img width="898" alt="screen shot 2018-03-02 at 3 06 27 pm" src="https://user-images.githubusercontent.com/4237045/36919613-eb35e368-1e2b-11e8-8c58-2761f25956b2.png">

**Comment by mturley** [comment]
I'm not sure whether this is necessary to fix, I kind of like the browser default behavior, especially when there is a long list.  We are a little inconsistent though in that we use react `DropdownButton` components for the source cluster selection, etc. What do you guys think?

**Comment by vconzola** [comment]
I still prefer the react dropdown. Have you asked Serena what she thinks?

VINCE CONZOLA

SR. INTERACTION DESIGNER, USER EXPERIENCE DESIGN

Red Hat <https://www.redhat.com/>

vconzola@redhat.com    T: 9197165041
<https://red.ht/sig>

**Comment by serenamarie125** [comment]
@vconzola I'm not 100% sure what you're refering to.  I think that this React Select seems much nicer + supports autocomplete.  What do you think?

**Comment by mturley** [comment]
There is already a non-native Dropdown Button component of some kind in the source selection at the top of some of the mapping wizard steps. Not sure if we want to just use that, or use something better in both cases.  @serenamarie125 did you mean to include a link? Which react select component are you referring to?

**Comment by mturley** [comment]
I think the one currently in the mapping wizard is what @vconzola is pointing to

**Comment by serenamarie125** [comment]
oops! http://jedwatson.github.io/react-select/

**Comment by priley86** [comment]
soooo.... we never got around to contributing react-select (and apologies for the confusion). This one is additionally confusing b/c we ended up starting the contribution w/ Downshift for Autocomplete, but it also supports [Dropdown](http://downshift.netlify.com/?selectedKind=Examples&selectedStory=dropdown&full=0&addons=1&stories=1&panelRight=0). These Downshift library components are completely generic / flexible APIs that are more a11y ready, but also more dynamic for future use cases (say you want to render icons or something else flexibly inside the dropdown/autocomplete). 

So if we want to try that library now w/ something simple and propose that to PF-React, I wouldn't be opposed. It looks like the Foreman team started w/ [select2](https://select2.org/) a long time ago, but I think they would be OK w/ moving to Downshift (as select2 was never finished in PF-React either)...

The simplest short term solution is keeping the native `select` or using `DropdownButton` (already in PF React)... so just depends on what we want to do at this point here...

**Comment by vconzola** [comment]
If I followed all this correctly it sounds like the Mapping wizard is
using DropdownButton
while the Plan wizard is using the native select. lan Short term, I prefer
the DropdownButton, but am not going to lose sleep as long as they're
consistent.

VINCE CONZOLA

SR. INTERACTION DESIGNER, USER EXPERIENCE DESIGN

Red Hat <https://www.redhat.com/>

vconzola@redhat.com    T: 9197165041
<https://red.ht/sig>

**Comment by serenamarie125** [comment]
For now, utilize the same component as in the mapping wizard - @michaelkro should be able to point you in the right direction.

**Comment by michaelkro** [comment]
Here is the component we're using in the Mapping wizard

**Comment by priley86** [comment]
Closing. This was done in #148
