### ISSUE TITLE
Create the Migration Completed Cards

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#11]
This issue will handle creating the UI components for the Migration in Completed Cards.

Subject to UX approval: 
These will be using the Aggregate Status pattern referenced here:
http://www.patternfly.org/pattern-library/cards/aggregate-status-card/

There is also a PF React issue here for Base Card :
https://github.com/patternfly/patternfly-react/issues/192

We will need to ensure the Base Card created supports Aggregate Status and then add any enhancements for Aggregate Status.

**Comment by serenamarie125** [comment]
<img width="575" alt="screen shot 2018-02-03 at 12 39 31 am" src="https://user-images.githubusercontent.com/12504403/35763461-beae626e-087a-11e8-8c2b-669dc009eb7f.png">

**Comment by priley86** [comment]
High fidelity design is here:
![v2v overview page-populated 2 2x](https://user-images.githubusercontent.com/4237045/36450638-9957c416-165c-11e8-9752-b6107b6afae9.png)
