### ISSUE TITLE
Actions and reducers for migration / migration status

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#12]
This should include actions + reducers + tests for API interactions around migration status (in progress/complete)

**Comment by priley86** [comment]
also starting the scaffolding for these.

**Comment by priley86** [comment]
Ready to get going on these next...

**Comment by priley86** [comment]
It looks like APIs have now been posted: https://gist.github.com/bzwei/3213174ee5efb4e377d789df8394cf2b

cc: @jeff-phillips-18

**Comment by jeff-phillips-18** [comment]
This work is included in #82 and #86
