### ISSUE TITLE
(Once re-enabled), number buttons are clickable in the second run of Infrastructure Mapping Wizard

### ISSUE THREAD

**Issue by AparnaKarve** [priley86/miq_v2v_ui_plugin#121]
Steps to reproduce -

1. Go through the Infrastructure Wizard steps all the way to Step5 and hit Close
2. Start the Infrastructure Mapping Wizard again. This time around the number buttons are clickable.

NOTE: currently only visible if you remove the `stepButtonsDisabled` prop from both instances of `<ModalWizard.Body>`. This is a bug in that disabled behavior, to be fixed when we re-enable it.

**Comment by mturley** [comment]
As I've brought up on slack, this would be fixed by adding a state property for `farthestSeenStepIndex` and using that for `disableGoto` instead of the current implicit redux-form behavior it is based on.

**Comment by priley86** [comment]
@AparnaKarve - it looks like this issue was fixed somewhere along the way. Can you confirm/close?

**Comment by AparnaKarve** [comment]
@priley86 Yes, I can confirm that this has been fixed.
