### ISSUE TITLE
Long term look at using something like React Select rather than dropdown

### ISSUE THREAD

**Issue by serenamarie125** [priley86/miq_v2v_ui_plugin#126]
Rather than using dropdown, look into utilizing something like [React Select](https://jedwatson.github.io/react-select/) which optionally supports search & clear as well. 

Currently the dropdown is used in both the infrastructure mapping and migration plan wizard.

Note that this ^^ should like be contributed to PatternFly React first.

**Comment by priley86** [comment]
Referenced in #140

**Comment by priley86** [comment]
We've gone w/ the existing MIQ select/typeahead for now. I referenced this in https://github.com/patternfly/patternfly-react/issues/54 for future. Closing...
