### ISSUE TITLE
Actions and reducers for migration plans

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#13]
This should include actions + reducers + tests for API interactions around migration plans 

Posting the execution of the migration plan

**Comment by mturley** [comment]
Starting this next, shouldn't take much time at all on top of what we have already.

**Comment by mturley** [comment]
This ended up getting delayed due to issues with the wizard code last week, and now is part of Aparna's upcoming PR. Apologies for my above comment-- "starting this next" turned into letting Aparna start it while I debugged other things.
