### ISSUE TITLE
Step 5 Duplicate Name / Unhappy path

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#134]
Found while debugging locally earlier today... We still need to address the following "unhappy" pieces in step 5:

* 400 Error for "Bad Name" - the user has duplicated the Mapping Name (from step 1) and the backend fails when creating the Mapping on Step 5. We should probably make an exception here to let them go back to step 1 (but will let @serenamarie125 @vconzola give best advice on what to do there).

* Retry button - the Retry button on Step 5 is not yet wired, however, I'm not sure we want it to be. Typically if you fail a POST - it's for a reason. Maybe we should change the messaging and not allow the user to retry until they've gone back to prior steps based on specific error codes returned. Will try to investigate those responses more.

**Comment by vconzola** [comment]
@priley86 Can we query the list of existing mappings when the user selects Next on page 1 of the mappings wizard? If duplicate, don't let the user proceed to cluster mapping.

**Comment by priley86** [comment]
@vconzola yes - i think we should change the UX to be a dropdown on Step 1 after having discussed it. Let's confirm w/ @serenamarie125 though and happy to fix it.

**Comment by priley86** [comment]
For the APAC demo - they are just going to be extra cautious to not use a duplicated mapping name...

**Comment by AparnaKarve** [comment]
@priley86 There is also a possibility of preventing this error upfront as part of the form validation in Step1 and block the "Next" button.
When the user types in a name, we could look up the `transformationMappings` array in `overview`, and check if the typed in name matches any of the existing record names. If there's a match, display "Duplicate Name" (in red, like we do for the "Required" field) underneath the Name field.

**Comment by priley86** [comment]
yes - sorry, something of that nature was what I had in mind as well @AparnaKarve. @serenamarie125 @vconzola maybe you'd like to clarify the behavior further in a UX/balsamic real quick for us...

**Comment by vconzola** [comment]
What I was thinking is... When user selects Next on the page, check if the name is unique. If not, display the inline error and highlight the Name field. This follo
![4a-createmapping-general w inline error](https://user-images.githubusercontent.com/22823035/37172787-cb7e4fde-22df-11e8-9b1c-a8f3ad20afec.png)
ws the PatternFly Errors and Validation pattern.

**Comment by AparnaKarve** [comment]
@vconzola We currently disable Next if the form is invalid.

Also, we display the error text (like "Required") when the user touches a Required field does not enter the Name and moves to the next field.

Would be better if we adhere to this behavior for the Duplicate Name validation as well.

**Comment by AparnaKarve** [comment]
@vconzola On second thoughts, I think what you suggested above might be the way to go for this specific case.

**Comment by priley86** [comment]
@michaelkro do you want to try this out tomorrow morning?

**Comment by michaelkro** [comment]
👍

**Comment by michaelkro** [comment]
closed by #139
