### ISSUE TITLE
Create Overview Migration Plan Cards and Filters

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#151]
Per the new UX, we will be able to visualize Migration Plans and filter them by status. Please provide corresponding UX screenshots @vconzola @serenamarie125 .

**Comment by vconzola** [comment]
@priley86 Mockups with the behavioral details for migration plan cards: https://docs.google.com/presentation/d/1e49cH7F0njW7rVA8qCMeu_FuQ9wNVWViYd2frbQukRQ/edit?usp=sharing

**Comment by priley86** [comment]
starting this based on current mock ups... will integrate backend APIs as they become available.

**Comment by vconzola** [comment]
I updated the UX document to include toast notifications when a plan completes migration, so be sure to reference the latest. Link is above.

**Comment by priley86** [comment]
Resolved in #212
