### ISSUE TITLE
Plan Wizard Step 1: Select from a discoverable list

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#153]
Per the new UX, we will need to be able to discover a list of VMs. Can you confirm @serenamarie125 @vconzola ?

Additionally, @AparnaKarve can you gather the API details returned?

**Comment by priley86** [comment]
already captured in #138  oops!

**Comment by serenamarie125** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [VM selection based in infrastructure mapping](https://trello.com/c/gWoFFLsf/109-vm-selection-based-in-infrastructure-mapping)

**Comment by bthurber** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1564238
