### ISSUE TITLE
Plan Wizard Step 2 - CSV Import Enhancements

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#154]
Upcoming/tentative UX changes:

* Change CSV empty state to PatternFly empty state or a design approved one? ** let's change about this
* Ensure that client side validation checks of CSV input give the user an error and we do not call the backend (these can be as minimal or as extensive as we decide them to be for now, but should at least include some basic formatting validation)
* Show the CSV import in a paginated table (instead of list view) after CSV import success. Ensure that all backend validation scenarios are handled and can be visualized in the table. 

can you confirm @serenamarie125 @vconzola ?
=== there are still some open questions here ... 

1. How are we showing an error if the plan fails validation. Modal? What's the message?
2. How are we showing invalid entries from the list?
3. Are all "valid" VMs from that list automatically checked
4. Are invalid VMs unchecked?

@AparnaKarve can you gather API details on backend validation?

**Comment by AparnaKarve** [comment]
API info here - https://github.com/priley86/miq_v2v_ui_plugin/issues/138#issuecomment-374744468

The API specified in the above link will provide us with a list of -
- valid VMs
- invalid VMs
- conflict VMs (There is a possibility of finding multiple VMs in the DB based on the information in the CSV)

-----

How to process the above API output -
- *Only* valid VMs can be selected for migration
- Invalid VMs can't be selected
- VMs in conflict -- TBD (hard to decide at the moment, and more work will be needed to work on the details)

**Comment by serenamarie125** [comment]
<img width="868" alt="screen shot 2018-03-21 at 8 50 27 pm" src="https://user-images.githubusercontent.com/12504403/37746726-93e36ef0-2d49-11e8-9753-8c69a27cb214.png">

<img width="909" alt="screen shot 2018-03-21 at 8 50 33 pm" src="https://user-images.githubusercontent.com/12504403/37746727-970783fa-2d49-11e8-9498-6a86b25d137b.png">

<img width="869" alt="screen shot 2018-03-21 at 8 50 39 pm" src="https://user-images.githubusercontent.com/12504403/37746728-998011c4-2d49-11e8-99c7-93d440a2ded1.png">
Note that the above table is exactly the same as if you browse, EXCEPT there is an Import button on the toolbar.

**Comment by AparnaKarve** [comment]
@serenamarie125 Is the component in the above mockup a [List](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Stacked=false&selectedKind=ListView&selectedStory=List%20of%20expandable%20items&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) or a [Table](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Stacked=false&selectedKind=Table&selectedStory=PatternFly%20Table%20Styles&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)?

**Comment by vconzola** [comment]
@AparnaKarve It's a table.

**Comment by serenamarie125** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(debt) VM import from file enhancement](https://trello.com/c/QlW2xY9J/96-debt-vm-import-from-file-enhancement)

**Comment by priley86** [comment]
Closed by #192  - will revisit other enhancements in future issues.
