### ISSUE TITLE
Overview Migration Plan Cards - Richer error reporting

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#157]
For each VM in a migration plan, the user should be able to see:
- progress of the migration
- last message associated with the migration of that VM

would like to visualize the richer error details happening during plan execution.

@AparnaKarve do you have any Automate API details you'd like to share at this point?

**Comment by priley86** [comment]
Further detail describing the state transition will be provided. A.t.m., this is the most information we have: https://gist.github.com/bzwei/3213174ee5efb4e377d789df8394cf2b#file-v2v_example-json-L431

**Comment by serenamarie125** [comment]
@priley86 again just checking, thinking we can remove the needs-api label?  Please confirm

**Comment by priley86** [comment]
Yep finishing these last few up now.

**Comment by priley86** [comment]
Resolved in #212
