### ISSUE TITLE
User should be able to start a migration plan that has not yet been run

### ISSUE THREAD

**Issue by serenamarie125** [priley86/miq_v2v_ui_plugin#159]
Per the new UX, users can start a migration plan that has been saved for later.

Please provide corresponding UX screenshots @vconzola

**Comment by vconzola** [comment]
![overview - w all copy 2 filter is not started](https://user-images.githubusercontent.com/22823035/37733742-6f2b7212-2d1f-11e8-8bc7-c94ae2d5b504.png)
 Behavioral details are in this file (slide 4): https://docs.google.com/presentation/d/1e49cH7F0njW7rVA8qCMeu_FuQ9wNVWViYd2frbQukRQ/edit?usp=sharing

**Comment by serenamarie125** [comment]
I think we need some clarity on the designs for this.  I've added some comments in the above deck

**Comment by priley86** [comment]
@AparnaKarve can you clarify what status code will be used to indicate "migrations not started"?

**Comment by serenamarie125** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create migration plan without running](https://trello.com/c/RDjIR9O1/110-create-migration-plan-without-running)

**Comment by priley86** [comment]
A migration plan that has been created but not yet run will have a "Queued" status. A migration request that has been created but not yet run will have "Pending" status. We can discuss further UX implications tomorrow...

**Comment by serenamarie125** [comment]
@michaelkro @priley86 can you confirm that we are no longer blocked by API?

**Comment by priley86** [comment]
Yep good to go 👍

**Comment by priley86** [comment]
Resolved in #212
