### ISSUE TITLE
Create the Migration Plan Wizard 

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#16]
This will involve the following:

* 1. create the general step for specifying mapping / description
* 2. create the import vm's step for importing vms and validating them if possible
* 3. create the results step indicating a migration is in progress

**Comment by serenamarie125** [comment]
@priley86 can we close this in lieu of #30 ?

**Comment by priley86** [comment]
yep, thanks the further breakdown and descriptions on those!
