### ISSUE TITLE
Migration nav item should not have any sub items & should show what's currently in Overview

### ISSUE THREAD

**Issue by vconzola** [priley86/miq_v2v_ui_plugin#161]
Initially we thought that there would be 3 sub items under Migration, but Vince has come up with a great way to have everything on a single page.  

This issue should consist of:
- Removing sub items from the **Migration** nav item
- Display current **Overview** content when selecting **Migration**

NOTE: In the future, we might want to add it back as new features are added that will necessitate a separate mappings page and nav sub items. So maybe just comment out the code?

**Comment by serenamarie125** [comment]
@vconzola not only that, if we have everything on the overview page, I'm assuming that we can just have "Migration" without any children at all. If you agree, we can change the title of this issue to be something like _the Migration nav item shouldn't have any sub items_

We would also need to decide if the title of the page remains "Migration Overview"

**Comment by AllenBW** [comment]
@serenamarie125 @vconzola is this to mean we're trashing the content of this component?  (the one holding a screen shot)
<img width="1066" alt="screen shot 2018-03-22 at 5 10 32 pm" src="https://user-images.githubusercontent.com/6640236/37798718-f4144bd2-2df3-11e8-9a84-e2dc9f31d886.png">

**Comment by vconzola** [comment]
@AllenBW For now, yes, you can trash the link to the screenshot. Long term, when we add the ability to edit, delete, archive, and comment on mappings we might want a separate Infrastructure Mappings page, but for now there's no reason to show it since the most important information is available on the Overview page.

**Comment by AllenBW** [comment]
@serenamarie125 @vconzola Ok so we have a rub with this ask...

What it boils down to is this, right now, can't add a two menu item into a three menu item list... what's that look like? 

## services is a two menu item list, compute is a three
<img width="450" alt="screen shot 2018-03-26 at 8 34 20 am" src="https://user-images.githubusercontent.com/6640236/37906632-c13706fc-30d0-11e8-96dd-cbea2f88e13d.png">
<img width="679" alt="screen shot 2018-03-26 at 8 34 10 am" src="https://user-images.githubusercontent.com/6640236/37906633-c14198c4-30d0-11e8-87e2-dc353ccda357.png">

SO what are present options:  
* new single tiered list (you would see this on top level)
* refactor single item three tiered list (which would "auto launch" the default item on second tier click, kinda behave like a single tiered item)
* relocate into existing migrate to a two tiered list 
* figure out why we can't do this thing and attempt to change it

If ya wanta take a look at what the options might look like.... lets do a 👖 !

**Comment by vconzola** [comment]
@AllenBW Dang! I was afraid that might be a problem. I guess another option is to just leave the nav as is with the Infrastructure Mapping page a static .PNG and just ignore it in any demos. Or include it in demos and explain that in the future there will be additional features for infra mappings like edit, delete, archive, and comment.

@serenamarie125 What do you think?

**Comment by AllenBW** [comment]
OK never mind, I lied.. @vconzola @serenamarie125 

@ZitaNemeckova came up with a neat fix... will yield the desired result below.... 

<img width="752" alt="screen shot 2018-03-26 at 11 09 51 am" src="https://user-images.githubusercontent.com/6640236/37914968-7129e7c2-30e6-11e8-90dd-a140cc29b158.png">


Gonna make a few prs to get this going...

**Comment by serenamarie125** [comment]
@AllenBW I love it when you lie like that 😂 

Thanks to you and @ZitaNemeckova for finding a solution 👏

**Comment by AllenBW** [comment]
github closes tag. YOU ARE FAILING ME!!!!?!?! :rage4:
