### ISSUE TITLE
v2v screens ask me to login again

### ISSUE THREAD

**Issue by Fryguy** [priley86/miq_v2v_ui_plugin#162]
![monosnap 2018-03-21 15-55-26](https://user-images.githubusercontent.com/52120/37734185-d3917ad4-2d20-11e8-917b-ea6878805df9.png)

If I Cancel or Login, it just keeps popping up, and because it's a modal, I'm stuck on this page forever.

**Comment by himdel** [comment]
This *probably* means v2v is not accessing the api via the `API` global (well, `vanillaJsAPI` outside angular, [for now](https://github.com/ManageIQ/manageiq-ui-classic/issues/3658)). Otherwise this would trigger a login screen redirect.

No idea about the loop though.

**Comment by priley86** [comment]
good to know - and thanks for the issue. I think we can look at this next sprint potentially.

**Comment by AparnaKarve** [comment]
Yes, we need to associate the token to `API`

Surprisingly, I have seen the login popup only once or twice so far... 

As far as the loop goes, I think that's not the case based on the gitter chat with @Fryguy

**Comment by priley86** [comment]
ok - please feel free to introduce this as you have time @AparnaKarve. I was not aware on this piece and thanks for following up ;)

**Comment by priley86** [comment]
Closed by #166
