### ISSUE TITLE
Plan Wizard Step 2 - Browse / Empty State

### ISSUE THREAD

**Issue by serenamarie125** [priley86/miq_v2v_ui_plugin#164]
In step 1 of the wizard, if browse is selected, step 2 should look like this:

<img width="872" alt="screen shot 2018-03-21 at 8 50 18 pm" src="https://user-images.githubusercontent.com/12504403/37747052-28d805d8-2d4b-11e8-9632-0da6d8a224dd.png">

Note that this table is the same as used for #138.  There are a couple small differences:
1. in this case, the table is populated by available VMs determined by the migration plan
2. The import button which is available on the toolbar when import, is NOT shown in this case

**Comment by serenamarie125** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [VM selection based in infrastructure mapping](https://trello.com/c/gWoFFLsf/109-vm-selection-based-in-infrastructure-mapping)

**Comment by priley86** [comment]
It looks like the following API (currently in progress) can be mocked for Step 2 of the Plan Wizard browsers/validation features.
https://github.com/ManageIQ/manageiq/pull/17177/files

**Comment by mturley** [comment]
Thinking I will get this one done tonight so I can finish the wizard abstractions tomorrow.

**Comment by priley86** [comment]
Would like to repurpose this issue to "Correct the empty state visualization" for Step 2 - Browse. Per discussion w/ @vconzola @serenamarie125 , we'd like to show the PF React Empty State with the Browse button centered (how it is in PF React). We'd also like to change the Empty State Icon to be the PatternFly "pficon-import" icon (the same one that's used in the Table Action). 
![screen shot 2018-04-12 at 3 28 26 pm](https://user-images.githubusercontent.com/4237045/38699609-7cac4ecc-3e66-11e8-9556-0890393cd096.png)


@mturley do you think you can help?

**Comment by serenamarie125** [comment]
Closing - additional UX requests have been added as separate issues
