### ISSUE TITLE
Migration Cards should start with a pending label

### ISSUE THREAD

**Issue by serenamarie125** [priley86/miq_v2v_ui_plugin#165]
Currently, there's a lag once migration starts, and the cards are not updating immediately.  When a migration is initiated but not yet started, show the progress card with a "Pending" label.

**Comment by serenamarie125** [comment]
@vconzola 

Do you think we should show use the BS Spinner or the fa-hourglass?

<img width="211" alt="screen shot 2018-03-21 at 9 35 27 pm" src="https://user-images.githubusercontent.com/12504403/37747983-cdc6dc78-2d4f-11e8-8b7d-ad9701c07f06.png">

I think the placement of icon & label should be similar to the [Loading State of the Base Card](http://www.patternfly.org/pattern-library/cards/base-card/#design)

![card-loading](https://user-images.githubusercontent.com/12504403/37748020-0610df16-2d50-11e8-839c-b12d65d29955.png)

**Comment by vconzola** [comment]
@serenamarie125 Good points. This is one of the things I still need to mock up. As for the icon, I'm already using the hourglass variations for the different migration states, which I'm not crazy about. Was planning to ask Jenny or Kyle for their thoughts.

**Comment by serenamarie125** [comment]
@priley86 do we need any API support for this, or are we all set?

**Comment by serenamarie125** [comment]
@mturley 
Mock is here:  https://docs.google.com/presentation/d/1e49cH7F0njW7rVA8qCMeu_FuQ9wNVWViYd2frbQukRQ/edit#slide=id.g35289d819d_0_0. 
<img width="559" alt="screen shot 2018-04-13 at 6 34 14 pm" src="https://user-images.githubusercontent.com/12504403/38760465-6448f522-3f49-11e8-85b3-bbb5e5484d77.png">

Please mimic placement of icon & label similar to the Loading State of the Base Card

**Comment by vconzola** [comment]
@serenamarie125 Any suggestions on how to dismiss a plan (see mockup above) that fails while in Pending state? Have you seen any examples where bar utilization or other cards can be closed? My initial ideas are adding a close button to the card when the error is displayed or displaying a toast notification with a close action. (This would require user to be watching when the plan fails.) Don't know if there's any precedent to follow in other products.

**Comment by mturley** [comment]
@priley86, I spent today addressing a few other things, and fixing my local manageiq environment again... I'm ready to dive into this first thing tomorrow, but you mentioned starting it in #212-- can we chat in the morning about what's next here?  I may grab another issue since this one seems to still have some design discussion going on.

**Comment by priley86** [comment]
will additionally need a way to remove the "pending" state if auto-cancelling after 5 minutes.

**Comment by vconzola** [comment]
@mturley Follow the mockup below. 
- Placement of icon & label should be similar to the [Loading State of the Base Card](http://www.patternfly.org/pattern-library/cards/base-card/#design).
- Icon should be [this gif]: (https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/spinner.html)
![overview - w all copy 3 filter is in progress - pending](https://user-images.githubusercontent.com/22823035/38890560-c4eaef9e-424f-11e8-8fbf-df454e4433cd.png)

**Comment by vconzola** [comment]
@priley86 I think we decided to create a new issue for the case where a pending plan times out. So this issue will only involve making sure the the pending card matches the design spec above.

**Comment by priley86** [comment]
ok @vconzola - no problem. Just making sure it wasn't lost ;)

**Comment by mturley** [comment]
Thanks for the updates @vconzola. I've got work to push for this soon.

**Comment by priley86** [comment]
closed by #245
