### ISSUE TITLE
Migration cards for migration in progress should show additional progress of data that's been migrated

### ISSUE THREAD

**Issue by serenamarie125** [priley86/miq_v2v_ui_plugin#169]
Migration cards for migration in progress should have additional progress shown.  

User wants to see the amount of data (allocated size of a VM) that's been migrated per plan

**Comment by serenamarie125** [comment]
@priley86 do we need API support for this?  If so, let's add the appropriate flag

**Comment by priley86** [comment]
@serenamarie125 added 👍

**Comment by AllenBW** [comment]
chiming in to follow this... just cuz it might land in my 🏓 🤔

**Comment by priley86** [comment]
we are not quite ready here - finishing up integrating other pieces on the Overview today and tomorrow, should be ready for this by Monday next week...

**Comment by serenamarie125** [comment]
@priley86 are we still blocked by api?  If not, let's remove the tag

**Comment by priley86** [comment]
Nope - working this one next to clear out the Migration ..will send you some screenshots soon!

**Comment by priley86** [comment]
Resolved in #212
