### ISSUE TITLE
User should be able to view all messages associated with a specific VM migration

### ISSUE THREAD

**Issue by serenamarie125** [priley86/miq_v2v_ui_plugin#172]
User should be able to view all messages associated with a specific VM migration

**Comment by vconzola** [comment]
@serenamarie125 @priley86 What design is needed for this issue?  Is this something beyond displaying a link to download the log file for a migration? And isn't the download just waiting for the API to be available? The mockup for that was in one of the multitude of other issues that were open last week.

**Comment by serenamarie125** [comment]
Closing because this is the same as #208
