### ISSUE TITLE
Modals break when upgrading patternfly

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#178]
I noticed yesterday that InfraMapping/Plan Wizard modals break/no longer open when I upgrade the `patternfly` dependency to `^3.42.0`.

@AllenBW do you think you can help?  This would also ensure the breadcrumbs correctly display the single arrow...

**Comment by priley86** [comment]
Unrelated... maybe you can verify this one after. This happened after upgrading to the PF-R Cards (with built in match height) in #177 
https://github.com/patternfly/patternfly-react/pull/296

**Comment by AllenBW** [comment]
ON THIS 👍

**Comment by priley86** [comment]
so much appreciation here 🙇 👍 🎄 ... will help a lot

**Comment by priley86** [comment]
so i think this is (and I keep forgetting this) due to the fact we are really referencing PF css in ui-classic (and not really in this repo). I would like to request that those maintaining UI-Classic can update the patternfly dependency in a future sprint if possible.

are you OK w/ the match-height fix @AllenBW ? I will vet it one more time and we can merge next week if so...

**Comment by AllenBW** [comment]
yeah about that ☝️@priley86 likely the reason why updating the deps does not  yield the single arrow breadcrumb ... 

about the match-height fix, looking for the diff in behavior between the current pfr and with your pr, not seeing one... what should i be looking for?

**Comment by AllenBW** [comment]
gosh gh... none of that issue auto close... what is going on!
