### ISSUE TITLE
Review componentRegistry pattern w/ mIQ Core

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#18]
In this issue we will follow up on the component registry pattern implemented here (and tested) and ensure it integrates with manageiq-ui-classic. Need to review if any components/containers need to be injected server-side (via mounts). Also need to review if we can support `ownProps` in the componentRegistry pattern implemented in manageiq-ui-classic.

**Comment by priley86** [comment]
We are using the latest `const { componentRegistry } = window.ManageIQ.react;` object in upstream ui-classic. Can this be closed @ohadlevy @vojtechszocs @himdel ?

**Comment by himdel** [comment]
@priley86 Yes, I think we can close this, we will keep the same API available when switching to the new component registry.

(The registries both solve different problems:

* `ManageIQ.react` assumes only react components, taking `data` and `store` as props, and lets you get at the actual component to use it from react,
* `ManageIQ.component` doesn't assume the framework, but does redux via Provide, not store=, and lets you pass in props with different names than `data` and `store`, but does not currently allow the simple react-in-react version

so merging the two will involve some more thinking
)

**Comment by priley86** [comment]
Ok thanks a lot @himdel . I would love to revisit this in a future sprint (post Summit). I also have some more ideas about GraphQL / Redux I'd love to start exploring in a mIQ sandbox w/ you as I have time.

**Comment by priley86** [comment]
Closing for now.
