### ISSUE TITLE
Completed Migrations are not ordered atm

### ISSUE THREAD

**Issue by serenamarie125** [priley86/miq_v2v_ui_plugin#184]
QE reported that completed migrations are currently not in any specific order.

@michaelkro confirmed that currently the UI is showing them in the order returned by the API.  

Yadnyawalk from QE suggested that we consider to show latest migration notification request at the top of the table

@vconzola can you verify that this should be ordered in descending order by time?

Note that there is an associated BZ : https://bugzilla.redhat.com/show_bug.cgi?id=1565021

**Comment by serenamarie125** [comment]
Based on discussions #185 looks like descending by date/time has been confirmed.  @vconzola can you give me the 👍

**Comment by vconzola** [comment]
@serenamarie125 Yes, the default sort order for all of the Plans views should be descending by date.

**Comment by AparnaKarve** [comment]
Fixed in https://github.com/priley86/miq_v2v_ui_plugin/pull/199
