### ISSUE TITLE
Enhancement request to have Completed Migrations support sort

### ISSUE THREAD

**Issue by serenamarie125** [priley86/miq_v2v_ui_plugin#185]
Yadnyawalk from QE requested that we consider supporting sorting for completed migrations:

> If possible, can we also have sorting filters for migration_name, successful/unsuccessful status and time row in ↟/↡ order. With that mean, alphabetical order for name/status stuff and numbers for time, I marked it under LOW priority

**Comment by serenamarie125** [comment]
@vconzola have you addressed this in any forward looking designs yet?

**Comment by priley86** [comment]
as far as sorting goes... typically handled by backend query/backend team. @AparnaKarve can you check if the query would support a sort order parameter coming from the front end?

**Comment by vconzola** [comment]
@serenamarie125 No, I haven't added it to any of the Overview mockups. If it can be handled by the backend so that the most recent plans at the top, I'd rather not clutter the Overview with sorting/filtering controls. If/when we add dedicated pages for mappings and plans sorting and filtering are already in the mockups for those. My goal is to keep the Overview as close to a dashboard as possible.

**Comment by vconzola** [comment]
@priley86 @AparnaKarve What ever sort order parameter we send to the backend to get the most recent completed plans at the top, we should also send for in progress and not started plans. (I'm guessing it's all the same query, but I'm not sure.)

**Comment by AparnaKarve** [comment]
The sorting parameters that the API supports are -

`sort_by=attribute_name`
`sort_order=asc` / `sort_order=desc`
`sort_options=ignore_case`

**Comment by serenamarie125** [comment]
I agree @vconzola, for this issue we don't need to add a sort control for the user, we just need to determine the default sort order.  Seems like it's descending by date.

**Comment by vconzola** [comment]
@serenamarie125 Yes, the default sort order for all of the Plans views should be descending by date.

**Comment by AparnaKarve** [comment]
@priley86 Yes, we can close this out.
