### ISSUE TITLE
Input fields should have max character limit

### ISSUE THREAD

**Issue by serenamarie125** [priley86/miq_v2v_ui_plugin#186]
As reported by Yandyawalk from QE, input fields should have a max character limit.

Fields which requires limit:
1. Infra mapping's Name and Desc
2. Migration Plan Wizard's Name and Desc
3. VM Name of CSV file (This limit should be equivalent to vCenter's VM name limit)

Those limits are still "tbd" ... but this is captured by this BZ as well : https://bugzilla.redhat.com/show_bug.cgi?id=1565065

Edit: current proposed limits are 24 for names and 128 for descriptions.

**Comment by serenamarie125** [comment]
@vconzola can you follow up on this?  At a minimum we should be preventing the user from getting themselves into trouble by entering a VM Name that's too long from a vCenter perspective

**Comment by vconzola** [comment]
@serenamarie125 I did some digging, and even enlisted Kendra's help, and all I was able to find is an 80 character limit for VMware VM names, 24 characters for DNS host names, and 256 chars for descriptions. since our users won't be naming VMs (they're copied over from VMware), I think the real issue is making sure that RHV can handle VM names up to 80 characters. I found conflicting information on that, but someone from the RHV team should know. 

it looks like @AllenBW has already solved the truncation problem in the mapping lists issue #188 . for us, the only info that users enter are mapping names, plan names, and descriptions. so i'm not sure what's behind the BZ. if it's a simple matter of QE wanting length limits we can make them whatever we want (within reason), right?

**Comment by priley86** [comment]
bump... i think @AllenBW would like to grab this one next...

**Comment by AllenBW** [comment]
<img width="549" alt="screen shot 2018-04-24 at 9 50 34 am" src="https://user-images.githubusercontent.com/6640236/39191503-0c7efbca-47a5-11e8-94e8-7b6621da48b6.png">


we have developments, yah, theres the limit,

**Comment by AllenBW** [comment]
[To be implemented as per pfr, text validation criteria below field](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Disabled=false&knob-Show%20Labels=false&knob-Validation%20State=&knob-Show%20Help=true&knob-Field%20Level%20Help%20Content=Please%20specify%20Country%20code%20%3Cbr%3E%20%3Ca%20target%3D%27_blank%27%20href%3D%27https%3A%2F%2Fcountrycode.org%2F%27%3EClick%20here%20for%20a%20list%20of%20Country%20codes%3C%2Fa%3E&knob-Close%20Popover=true&knob-Show%20Loading=true&selectedKind=Forms&selectedStory=Vertical%20Form&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

**Comment by mturley** [comment]
@AllenBW are you still doing this one? I can grab it if you like, I just freed up.

**Comment by mturley** [comment]
Here are some screenshots of the 3 states we have for validation of each field. @vconzola, I need to determine the text we want to use for:
* initial help/description (if any) in grey (screenshot 1, we could use this to announce the character limit before input if we want)
* Empty on unfocus (screenshot 2, currently says "Required" in red, which is probably fine)
* Over the character limit (screenshot 3, currently is a little weirdly phrased).

![screen shot 2018-04-26 at 1 51 40 pm](https://user-images.githubusercontent.com/811963/39324626-f7c50bba-495d-11e8-80ec-5a6013825018.png)

![screen shot 2018-04-26 at 1 51 29 pm](https://user-images.githubusercontent.com/811963/39324638-00763a2c-495e-11e8-96ad-0c703db0d321.png)

![screen shot 2018-04-26 at 1 51 17 pm](https://user-images.githubusercontent.com/811963/39324646-05ae281a-495e-11e8-96c8-7e3d1e156478.png)

**Comment by vconzola** [comment]
@mturley Here's some text:
For initial help/description for Name field: "Maximum is 24 characters."
For initial help/description for Description field: "Maximum is 128 characters."
Empty on unfocus for Name field: "Required"
Empty on unfocus for Description field: blank - field is not required and don't turn it red
Over the character limit for Name field: "Name is too long. Maximum is 24 characters."
Over the character limit for Description field: "Description is too long. Maximum is 128 characters."

Let me know if you have any questions.

**Comment by mturley** [comment]
Perfect, thanks @vconzola. I'll use those. For the description field being left blank, it won't say "Required" or turn red, or go blank-- with no error, it'll just show the initial help/description.

**Comment by mturley** [comment]
@vconzola since the max character info now disappears when you get the validation error, and 'Required' was the only validation error to not have that info, I think I'm going to use "Required. Maximum is 24 characters." for that message. Sound ok?

**Comment by mturley** [comment]
I guess it's fine without that, I can go back to just 'Required' there if we want.

**Comment by vconzola** [comment]
@mturley I like "Required. Maximum is 24 characters." Good idea.

**Comment by mturley** [comment]
@vconzola here's a recording of where we are with these in place. Bringing this over to the other wizard now and I'll have a PR up in a minute.

http://recordit.co/aEd8yjVuYo

**Comment by mturley** [comment]
@serenamarie125 I'm going to make a PR just for the names and descriptions (the first 2 in your list up top here). You mentioned that the VM step has validation that isn't part of this issue, but is any of that step part of this issue? Adding validation in the CSV Dropzone won't be quite the same, so either way let's handle it as a separate change.

**Comment by mturley** [comment]
https://github.com/priley86/miq_v2v_ui_plugin/pull/256

This should be mergeable and covers the name and description fields in both wizards. Let's merge this and then figure out if the CSV stuff should be part of this issue or another (not sure where the line is there, if there is more than one thing to validate in there and this covers the names of VMs, or if that's all covered in https://github.com/priley86/miq_v2v_ui_plugin/issues/206).

**Comment by vconzola** [comment]
@mturley I think the name of the .CSV file will be covered by #206. For the names of the individual VMs, I believe that validation will be done by the backend as part of the validation they do to confirm the VMs exist on the host clusters and are not duplicates. If a name in the CSV file matches a name on the source cluster(s) it must be OK. Since the VM names are being copied over for VMware to RHV, the question is really whether RHV supports the same naming conventions as VMware. And that's not really something our UI should have to worry about.

**Comment by serenamarie125** [comment]
@mturley - i agree with @vconzola.  What you've done is great!  Thank you

**Comment by mturley** [comment]
Ok. I only meant names of VMs, so I was a little confused. Are we validating the name of the CSV file? Doesn't seem like that filename should really matter, right? the file isn't being imported, just the referenced VMs.

**Comment by mturley** [comment]
Perfect, thanks @vconzola, that's what I figured. Good to confirm it.

**Comment by mturley** [comment]
Updates to the discussion around this issue are present on the PR here, which is now ready to merge: https://github.com/priley86/miq_v2v_ui_plugin/pull/256

**Comment by priley86** [comment]
Closed by #256
