### ISSUE TITLE
Add datacenter to cluster names in Create Infrastructure Mapping wizard

### ISSUE THREAD

**Issue by vconzola** [priley86/miq_v2v_ui_plugin#188]
Wherever we display a cluster name in the mapping wizard we need to append the  associated datacenter where it lives. I looked at a few different options and prefer that we show it as "datacenter_name \ cluster_name". 
![4aa-createmapping-clusters w datacentre - option 2](https://user-images.githubusercontent.com/22823035/38520253-43841d76-3c10-11e8-9ffa-ba64edb60304.png)

**Comment by serenamarie125** [comment]
Need to determine truncation, when needed

**Comment by AllenBW** [comment]
UGGGGHHHH github, close this shit #221 was merged!
