### ISSUE TITLE
Stub "Create Infrastructure Mapping" Wizard

### ISSUE THREAD

**Issue by mturley** [priley86/miq_v2v_ui_plugin#2]
This will probably need to be broken down further, but adding it as a high-level task to assign myself.

**Comment by mturley** [comment]
Tentative plan to start on this:

- [ ] Add a barebones wizard with only one step (or maybe a stub for each real step).
- [ ] in that "Step 1" render area, add an empty dropdown for source clusters (and maybe a reload button? probably just for testing, wasn't in the mock)
- [ ] create a reducer for clusters
- [ ] wire up the API (or stub API) to the cluster reducer
- [ ] wire up the cluster reducer to the clusters dropdown

**Comment by priley86** [comment]
@mturley do you mind starting this one? we just need a simple wizard flow at this point first - so we can enable the other wizard steps to be developed simultaneously. If you can stub the wizard steps indicators and the wizard back/next in the footer for infra mapping wizard that would be great. Let's just tackle that one first and try the planning wizard next...

**Comment by mturley** [comment]
Yep, I'm on it.

**Comment by mturley** [comment]
This will be closed by #38.
