### ISSUE TITLE
Possible to navigate backwards from final Plan Wizard step

### ISSUE THREAD

**Issue by michaelkro** [priley86/miq_v2v_ui_plugin#205]
User should not be able to navigate backwards in Plan Wizard once they've hit Step-4.  Reason being that at this point:

1. The transformation plan has already been created
2. If the user chooses to start the migration immediately in Step-3, the transformation plan request has also already been created

**Comment by priley86** [comment]
yep - this is a bug. Should not be able to navigate back once on Step 4 - just like in Mapping Wizard.

@AparnaKarve do you want to try this one next sprint?

**Comment by AparnaKarve** [comment]
@priley86 sure!

**Comment by priley86** [comment]
this was resolved in #210 . Closing.
