### ISSUE TITLE
Use .haml instead of .erb

### ISSUE THREAD

**Issue by ZitaNemeckova** [priley86/miq_v2v_ui_plugin#21]
Use `.haml` instead of `.erb` to be consistent with ManageIQ.

- [ ] ./test/migration/app/views/layouts/mailer.text.erb
- [ ] ./test/migration/app/views/layouts/mailer.html.erb
- [ ] ./test/migration/app/views/layouts/application.html.erb
- [ ] ./app/views/layouts/migration.erb
- [x] ./app/views/layouts/index.html.erb https://github.com/priley86/miq_v2v_ui_plugin/pull/25

It was brought up [here](https://gitter.im/ManageIQ/v2v?at=5a65fe97517037a212dba9a7).

**Comment by priley86** [comment]
Thanks! ...we can fix them all.
