### ISSUE TITLE
Plan Wizard - review Empty State pattern design

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#213]
Carried over from #164 in Sprint6
See: https://github.com/priley86/miq_v2v_ui_plugin/issues/164#issuecomment-380918985

**Comment by serenamarie125** [comment]
@vconzola can you add a mock here ?  showing that the button should be below the title and description text.  Also, the background of this should be transparent (don't make it grey just to make it grey )

**Comment by AllenBW** [comment]
@vconzola noticing this mock no longer has the "vms to be migrated" title in the upper left, is this intentional?

**Comment by vconzola** [comment]
@AllenBW Wow, good eye. I thought it might be confusing to say "VMs to be migrated" with an empty state, so I got rid of it. I'd still like it to be there when we display the table.

**Comment by AllenBW** [comment]
@vconzola its not presently there when displaying the table, want me to add it? 
<img width="1009" alt="screen shot 2018-04-20 at 11 26 03 am" src="https://user-images.githubusercontent.com/6640236/39059866-b0e97318-448d-11e8-8c76-97e5c6a3acba.png">

**Comment by vconzola** [comment]
@AllenBW Yes, please.

**Comment by AllenBW** [comment]
womp womp, merged
