### ISSUE TITLE
Center Aggregate Cards on Overview

### ISSUE THREAD

**Issue by michaelkro** [priley86/miq_v2v_ui_plugin#214]
Currently the row of aggregate cards is left justified.

What should the responsive behavior of the individual cards be?  Should they grow to fill the entire row with a fixed margin between them?  Or should they have a fixed max width with even spacing between each card?

**Comment by priley86** [comment]
i think i know a fix ;)

**Comment by serenamarie125** [comment]
@michaelkro i would think that they are 3/3/3/3 so will grow / shrink responsively

**Comment by priley86** [comment]
does this fix ? I was laying w/ the layout a lot last sprint and felt pretty comfortable...

https://github.com/priley86/miq_v2v_ui_plugin/pull/233

**Comment by michaelkro** [comment]
Closed by https://github.com/priley86/miq_v2v_ui_plugin/pull/237
