### ISSUE TITLE
Pagination does not reset when applying a filter while viewing details of a migration in progress

### ISSUE THREAD

**Issue by michaelkro** [priley86/miq_v2v_ui_plugin#215]
## Steps to Reproduce
1. Use `mockMode`
2. Select `Migrations in Progress` in the Migrations section dropdown, and click to view the details of an active migration
3. Skip ahead a few pages using pagination (go at least to page 3)
4. Using the filter dropdown, choose to filter by `status`.  Then use the second dropdown to choose a status.
5. The new list of filtered items populates the table, but notice that the pagination says that you are still on the 3rd (or 4th, 5th, etc) page.  Also notice that the `forward`, `backward`, and `move to end` buttons no longer work (the `move to beginning` button still works)

## Screenshot
![fullscreen_4_16_18__9_04_am](https://user-images.githubusercontent.com/15141412/38810598-409f5d2e-4155-11e8-8c5c-c76d3cd725be.png)

**Comment by priley86** [comment]
fixed in #226
