### ISSUE TITLE
User should be able to drill into the Migration Plan details from the Migrations Completed List View

### ISSUE THREAD

**Issue by serenamarie125** [priley86/miq_v2v_ui_plugin#218]
Allowing the user to click anywhere on a list view item in the Migrations Completed List View to drill into the migration plan details.

@priley86 we need to understand how this works since there can be an action button on this List View Item

@vconzola FYI

**Comment by serenamarie125** [comment]
@jeff-phillips-18 I think you have done something similar to this, correct?
Allow clicking on a list view item to Drill Down ... but then also have an action button which is selectable?  

<img width="715" alt="screen shot 2018-04-16 at 9 51 06 am" src="https://user-images.githubusercontent.com/12504403/38812985-bcaa9f40-415b-11e8-9a6f-1b7e1e8b0e59.png">

**Comment by jeff-phillips-18** [comment]
Yes, we have done that before. Just a matter of preventing the navigation when the click is on the button.

**Comment by vconzola** [comment]
@mturley Here's a mockup of what the details page should look like if you need it. You should be able to use exactly what @priley86 did for the details view for in progress plans. Let me know if you have any questions.
![11a-plan details as list in drill down - complete](https://user-images.githubusercontent.com/22823035/38956486-bed7747a-4325-11e8-821e-1082b2f3ffcc.png)

**Comment by michaelkro** [comment]
Closed by #249
