### ISSUE TITLE
simulate the backend for saving & executing plans …

### ISSUE THREAD

**Issue by serenamarie125** [priley86/miq_v2v_ui_plugin#223]
Pre work for summit activities
@priley86 please add description

**Comment by priley86** [comment]
spoof all the backend in a new "summit demo" branch. this will include spoofing the following apis and using local storage:

* creating mappings
* validating/discovering plans
* creating plans
* querying mappings
* querying plans


update static mocks for the following (for demo):
* source clusters/target clusters
* datastores
* networks

**Comment by priley86** [comment]
and...........help @vconzola setup MIQ on RHEL Linux laptop  🎩 💻

**Comment by vconzola** [comment]
@priley86 Woo Hoo!! I'll start scheduling some time for us to start working on this early next week.

**Comment by priley86** [comment]
we are 90%+ complete here?... we have a super cool demo to record and share in the UXD Summit Booth now (and will be posting that for others to view next week). Just made a few notes to continue iterating on from this morning's review w/ @vconzola :

**Infrastructure Mapping List**
- the Completed Time is not showing the localized time correctly for some reason. I think we should move that back to moment.js
- the target cluster is showing twice (in the same mapping). Not sure if this is a data issue but will inspect it some more soon.
![screen shot 2018-04-27 at 3 32 48 pm](https://user-images.githubusercontent.com/4237045/39381503-5a41c832-4a30-11e8-9e17-a55e5a37f405.png)

**Plan Wizard**
- if there is anyway to clear the default input autocomplete that Chrome gives us, that might be desired. This is obviously low priority.
- we will need to craft a CSV file that matches up with the default discovery VMs listed here for the demo
- there is a new feature request to jump directly to "Plans in Progress" if the user selects "start immediately" radio. @michaelkro is tackling this and adding to both branches (`uxd-summit-booth` and to `alpha`)

**Comment by priley86** [comment]
this was completed in the `uxd-summit-booth` branch. I am leaving that up for legacy reasons only, but this branch will no longer be maintained 😸
