### ISSUE TITLE
Consistent rules across ManageIQ repositories

### ISSUE THREAD

**Issue by himdel** [priley86/miq_v2v_ui_plugin#23]
(If this repo is *not* supposed to become a ManageIQ repo, please close this issue.)

In all ManageIQ repos, squash + merge is disabled, because we do **not** want squashed commits. There is huge value in having the whole history, especially when looking for bugs, backporting changes to earlier releases, etc. etc.

We also don't allow editor config files to be checked in, except for a generic `.editorconfig` which multiple editors can parse. I'm seing `.vscode` here.

Third, we use `yarn` not `npm`, and we explicitly don't check in `yarn.lock` except in release branches. I'm seeing `package-lock.json` here.

This repository should follow the same rules.

**Comment by priley86** [comment]
hey @himdel 👋 

I am fine with "merge commit" setting if that is the preference... will update it now.

I believe checking in the `.vscode` settings file only (for VS Code Editor) is a good practice for ensuring consistency amongst folks using VSCode. This removes the amount of setup time there for folks integrating prettier into their IDEs and seems to be a good practice. 
https://stackoverflow.com/questions/32964920/should-i-commit-the-vscode-folder-to-source-control

I am fine w/ `yarn` and prefer it too actually 👍  will update...

**Comment by himdel** [comment]
Thanks @priley86 , much appreciated :).


> I believe checking in the .vscode settings file only (for VS Code Editor) is a good practice for ensuring consistency amongst folks using VSCode. 

The `.vscode` bit, I'm not sure if this is a hard rule or not, @Fryguy can probably tell you more once he gets back..  But.. I think the idea is .. we either have to support all the editors, or none of them.

I mean.. I'm definitely not personally opposed to `.vscode`. But.. imagine having `.vscode`, `.idea`, `.vimrc`, `.CodeBlocks`, and a few others and this quickly becomes unmanageable.

Also, some people prefer to have their own settings, even minutely different from the `.vscode` config in the repo .. and suddenly they need to start ignoring their changes manually and ... let's not go there :).

We can always add a sample `.vscode` config to the wiki.

**Comment by priley86** [comment]
I guess VSCode has it's own workspace settings for user overrides ... i dunno - kind of mixed feeling about this. I am fine either way in this repo.

Created #24 for removing package-lock

**Comment by priley86** [comment]
ok removed VSCode settings for now...
