### ISSUE TITLE
v2v plugin tab appears with ManageIQ, should be Infrastructure Migration

### ISSUE THREAD

**Issue by bthurber** [priley86/miq_v2v_ui_plugin#234]
In the v2v plugin, the nomenclature listed for the browser tab identified as v2v ManageIQ.  This should read Infrastructure Migration or Migration
![image](https://user-images.githubusercontent.com/4692674/39009915-9d985ba0-43d2-11e8-8c48-2b702a03cb3a.png)

**Comment by priley86** [comment]
fixed in #235
