### ISSUE TITLE
Display an empty state if there are no plans in the state selected in the dropdown

### ISSUE THREAD

**Issue by vconzola** [priley86/miq_v2v_ui_plugin#243]
If the user selects a state (Not Started, In Progress, Complete) in the dropdown for which there are currently no plans we need to display an empty state. In discussing with @priley86 this is much easier an clearer than my original hair brained idea of disabling and enabling states in the dropdown.

Mockups below:
![migration plans empty state - not started](https://user-images.githubusercontent.com/22823035/39195918-df822656-47ae-11e8-8093-f07e4a97042c.png)
![migration plans empty state - not started empty- in progress](https://user-images.githubusercontent.com/22823035/39195924-e2ac0720-47ae-11e8-84a5-0c73d2a50b34.png)
![migration plans empty state - not started empty - complete](https://user-images.githubusercontent.com/22823035/39195932-e5a52358-47ae-11e8-901e-2dcc6ef432e0.png)

**Comment by priley86** [comment]
f.y.i - hitting these cases in #223 and implementing them now.

**Comment by priley86** [comment]
<img width="1427" alt="screen shot 2018-04-26 at 2 27 52 pm" src="https://user-images.githubusercontent.com/4237045/39324731-3400d398-495e-11e8-9311-0dd9ded63370.png">

<img width="1430" alt="screen shot 2018-04-26 at 2 28 01 pm" src="https://user-images.githubusercontent.com/4237045/39324738-3748323a-495e-11e8-8332-71ce22d14936.png">

**Comment by priley86** [comment]
this is done in the `uxd-summit-booth` branch - will port this over to `alpha` branch PR soon...

**Comment by priley86** [comment]
closed by #260
