### ISSUE TITLE
Integrate Plans API 

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#254]
per discussion this morning, there was a new proposed solution to integrate plans API on the Overview screen by @bzwei :

* load the plans in one API and then separately batch all requests/tasks in a separate API.

We should be careful to ensure that existing UX logic stays in tact (aggregate status counts, migration section filters, aggregated disks/vms). I am happy to review this w/ @AparnaKarve once she feels comfortable w/ the integration. 

@AparnaKarve - based on other things I have heard previously - it sounds that virt-v2v disks may not be available until post Summit? But we might be able to display some of the other detail integrated in a nightly build sooner?

Can you please keep us posted once you have an integration? If this drags into next week, I think we should keep @bthurber posted.

**Comment by priley86** [comment]
cc: @vconzola @serenamarie125

**Comment by bzwei** [comment]
Please see the sample API [output](https://gist.github.com/lfu/ce3a1cab7dcc920cccfc7786b7a83cb2)
The first one is an existing API that the UI is already using. It pulls all migration plans plus requests in one call.

UI should extract href for each request, and compose the body to make the second call to get all tasks for selected requests.

**Comment by priley86** [comment]
Closed by the #260 . Thanks @bzwei @AparnaKarve .
