### ISSUE TITLE
UI flicker on plan details

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#266]
After integrating the backend API in #260 , i noticed a bit of flicker on the plan detail screen. It would be great to add a loading spinner instead of showing the empty VMs messaging...

![flicker](https://user-images.githubusercontent.com/4237045/39452267-9c081552-4c9f-11e8-9f6d-290ac43c2eca.gif)

**Comment by priley86** [comment]
would be nice to tackle this in sprint7 if possible...

**Comment by mturley** [comment]
I can grab this if you like @priley86. I'm freeing up and it looks like the only other unassigned issue has `needs-api`.

**Comment by priley86** [comment]
Awesome! Feel free!

**Comment by priley86** [comment]
this was way more tricky than i expected (apologies on that)... pushed a fix in #286

**Comment by priley86** [comment]
should be fixed in tonight's nightly...can you confirm tomorrow @bthurber?

**Comment by serenamarie125** [comment]
Issue is closed by #286 which is now merged

**Comment by mturley** [comment]
Thanks @priley86 , sorry I got stuck and hadn't pushed my fix yet. Yours is better anyway.

**Comment by bthurber** [comment]
Seems to be resolved.
