### ISSUE TITLE
Summit UI - VM migration timer continues to run

### ISSUE THREAD

**Issue by bthurber** [priley86/miq_v2v_ui_plugin#272]
Migration plan timer is good.  Drilling down into the plan, individual VM migration timers still run

**Comment by bthurber** [comment]
![screenshot from 2018-05-01 10-40-25](https://user-images.githubusercontent.com/4692674/39480314-6720a03c-4d2d-11e8-8fea-db23dc7c32dd.png)

**Comment by bthurber** [comment]
![screenshot from 2018-05-01 10-41-15](https://user-images.githubusercontent.com/4692674/39480333-7b32eabc-4d2d-11e8-8a92-4ae04bb17e22.png)

**Comment by priley86** [comment]
fixed by #279 - should be in tonight's nightly...

**Comment by bthurber** [comment]
Verified fix in latest nightly.
