### ISSUE TITLE
 Timed Out migration screen keeps repeatedly prompting for login

### ISSUE THREAD

**Issue by kedark3** [priley86/miq_v2v_ui_plugin#283]
https://bugzilla.redhat.com/show_bug.cgi?id=1573547

@priley86 I believe Brett will reach out to you to prioritize this. Please review as it may be an urgent bug to fix.

**Comment by AllenBW** [comment]
Still working this... 's being a tricky one to peg down...

**Comment by AllenBW** [comment]
ok finally, getting somewhere, this happens when session has timed out and polling is still going on... (but before user interacts and is redirected to login)

**Comment by AllenBW** [comment]
So two issues: 
- on session timeout, user not being redirected to login state, (well they do but only after interaction with a MIQ proper asset, not a plugin asset)
- user time in a plugin does not count towards session activity, meaning, if your session timeout is set to 10 minutes, after 10 minutes in the plugin the user will be forced to login again when navigating outside of the plugin, [an issue for this second one has been made here](https://github.com/priley86/miq_v2v_ui_plugin/issues/290)

Ok tagging more people in on this.. I think a real nice solution to the first problem might be to, on session timeout automatically redirect the user to login state... @himdel @ZitaNemeckova thoughts on the acceptability of this solution?  (a fraction of me suspects there is a reason we don't do this already)

**Comment by imtayadeway** [comment]
@AllenBW that sounds correct to me

> (might be wrong on this one) session closer does not invalidate api token

You'll need to ensure you do a `DESTROY` to `/api/auth` for this!

**Comment by himdel** [comment]
So.. I think the issue may be that v2v is not using the shared API UI code. If it were:

* any API request would make extend the token lifetime
* you wouldn't get the login popup since it would redirect you to the login screen correctly

**Comment by himdel** [comment]
So, the first step should be to remove `app/javascript/common/API.js` and rely on `window.API`.

Then we can try to fix any remaining problems in the common code.

(Caveat: the idea was to finish first https://github.com/ManageIQ/manageiq-ui-classic/pull/3662. Until that is merged, it's not `window.API` but `window.vanillaJsAPI`)
