### ISSUE TITLE
Fix alignment issues on Step 2 of the Migration Plan Wizard

### ISSUE THREAD

**Issue by serenamarie125** [priley86/miq_v2v_ui_plugin#295]
Everything should be left aligned on the wizard page 
- Title
- Filter Control
- Horizontal Separator
- Table
- "# VMs" label

![image](https://user-images.githubusercontent.com/12504403/39650322-b56bf23e-4fb5-11e8-98d2-a3c8ce417180.png)

**Comment by AllenBW** [comment]
@serenamarie125 how left aligned is left aligned? everything in line with the "vms to be migrated" title? 

so maybe like this cept with the hr also in line? 
<img width="902" alt="screen shot 2018-05-10 at 10 51 09 am" src="https://user-images.githubusercontent.com/6640236/39876002-254ba73c-5440-11e8-9492-cc1b0dc078cc.png">

**Comment by AllenBW** [comment]
### Where we're now at...
<img width="904" alt="screen shot 2018-05-16 at 7 43 38 am" src="https://user-images.githubusercontent.com/6640236/40115006-fcad0504-58dc-11e8-8b30-5f611f0add30.png">

### Seems to align with pf documentation for toolbar filter control
<img width="945" alt="screen shot 2018-05-16 at 7 44 54 am" src="https://user-images.githubusercontent.com/6640236/40115032-161103a6-58dd-11e8-89ac-ebf2050353f0.png">
http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/

If this is 🌮 💃 @serenamarie125, will open a pr pronto
