### ISSUE TITLE
Actions and reducers for loading Clusters

### ISSUE THREAD

**Issue by mturley** [priley86/miq_v2v_ui_plugin#3]

**Comment by mturley** [comment]
Working this into my PR for #2.

**Comment by mturley** [comment]
Nevermind, @priley86 my PR for #2 will just be wizard stub only, no redux.

**Comment by priley86** [comment]
taking a stab at this now..

**Comment by priley86** [comment]
I've received mock api json and urls for retrieving source and target clusters. I should have a PR up on Monday for this.
