### ISSUE TITLE
Stub "Create Migration Plan" Wizard

### ISSUE THREAD

**Issue by serenamarie125** [priley86/miq_v2v_ui_plugin#30]
Simple wizard flow at this point first - so we can enable the other wizard steps to be developed simultaneously. 

There are 3 steps in the wizard:
- General
- VMs
- Results

Stub the wizard steps indicators and the wizard back/next in the footer for infra mapping wizard that would be great. Let's just tackle that one first and try the planning wizard next...

**Comment by mturley** [comment]
This will be closed by #38.
