### ISSUE TITLE
Compute of main navigation should be highlighted after selecting migration page

### ISSUE THREAD

**Issue by Yadnyawalkya** [priley86/miq_v2v_ui_plugin#301]
**Component** - UI

**Description** - `Compute` of main navigation not get highlighted (is not active) even after selecting `migration` page.

**Actual result** 
![screenshot from 2018-05-07 17-55-45](https://user-images.githubusercontent.com/10824880/39713655-25bf39ec-5245-11e8-9f3f-80770d8d5b7f.png)

**Expected result**
![screenshot from 2018-05-07 20-54-17](https://user-images.githubusercontent.com/10824880/39713508-98bda86c-5244-11e8-91a7-44a63f7761a0.png)

**Internal tracking**
https://bugzilla.redhat.com/show_bug.cgi?id=1575613

**Comment by priley86** [comment]
Fixed by #302 - please confirm @Yadnyawalkya

**Comment by Yadnyawalkya** [comment]
It is working now, we can close this issue.

![screenshot from 2018-05-15 16-36-23](https://user-images.githubusercontent.com/10824880/40053328-7aec76ea-585e-11e8-9118-0febcdaab3fa.png)

Thanks @priley86 and @AparnaKarve ! :1st_place_medal:

**Comment by AparnaKarve** [comment]
Thanks for confirming @Yadnyawalkya!
