### ISSUE TITLE
[QEDevCollab] Need ids for radiogroups in migration plan wizard

### ISSUE THREAD

**Issue by Yadnyawalkya** [priley86/miq_v2v_ui_plugin#305]
To carry our automation with widgetastic's [RadioGroup](https://github.com/ManageIQ/integration_tests/blob/c917ea6113212a3d401a6ba57b624a5fed18181f/widgetastic_manageiq/__init__.py#L1660) widget, we need ids on `radio groups` of `migration plan wizard`. Locations are,

1. `id` for `Select VMs` radio group `div` (from first wizard pane)
![screenshot from 2018-05-09 12-31-34](https://user-images.githubusercontent.com/10824880/39800496-9732a172-5385-11e8-8514-b2747d916bb5.png)
 

2. `id` for `Run migration plan` radio group `div` (from third wizard pane)
![screenshot from 2018-05-09 12-32-30](https://user-images.githubusercontent.com/10824880/39800766-893acd6e-5386-11e8-8602-7b1c2acc841d.png)

**Actual code**

```
<div class="col-sm-9">
  <div>
     <label for="migration_plan_choice_radio">
       <input name="migration_plan_choice_radio" value="migration_plan_later" type="radio">
         Save migration plan to run later
         ... ... ...
     </label><br>
  </div>
<div>
```

**Expected code**
```
<div class="col-sm-9" id="select_vm_radio_group">
  <div>
     <label for="migration_plan_choice_radio">
       <input name="migration_plan_choice_radio" value="migration_plan_later" type="radio">
         Save migration plan to run later
         ... ... ...
     </label><br>
  </div>
<div>
```
Please note both `ids` should be different. Let say, `select_vm_radio_group` and `run_plan_radio_group` (you are free to choose those name)

**Comment by AllenBW** [comment]
will go through and ensure all radio buttons gotta lil something something for yah today @Yadnyawalkya 🙇‍♀️

**Comment by priley86** [comment]
👍

**Comment by AllenBW** [comment]
@Yadnyawalkya so we could put them on groups.. or would putting them (ids) on individual fields be more useful?

**Comment by Yadnyawalkya** [comment]
@AllenBW - it'll be good if you put `id` on group, similar like what I did in expected code (In `div`). 
(Above statement is specifically for RadioGroup only. Incase of other widgets, individual ids will be preferable)

In automation point of view, we have widget functions which take `xpath` of `RadioGroup` and automatically detect `RadioButtons` in it, so this id will be use in that `xpath` to identify that `RadioGroups`. Individual `RadioButton` already have unique identification like `value="vms_via_discovery"` thus no need to add there.

**Comment by AllenBW** [comment]
right on! ok so how about this... rather than doing it for just radio... doing it for everyone, just in case you need them in the future? 
<img width="521" alt="screen shot 2018-05-09 at 10 12 10 am" src="https://user-images.githubusercontent.com/6640236/39819475-8addf7b4-5371-11e8-87ef-605a6d94f562.png">


@Yadnyawalkya if you're happy with ☝️ i'll 🗃 yah up a pr tout de suite!

**Comment by AllenBW** [comment]
Oh... hmm.... good to know... well its easiest just to add em to all, so disregard the others 😏

**Comment by AllenBW** [comment]
#306 closes this!
