### ISSUE TITLE
Elapsed Time Issue

### ISSUE THREAD

**Issue by kedark3** [priley86/miq_v2v_ui_plugin#312]
https://bugzilla.redhat.com/show_bug.cgi?id=1573510#c4

**Comment by priley86** [comment]
Merged #308 - please retest in the nightly.

**Comment by kedark3** [comment]
@priley86 @Yadnyawalkya is investigating this

**Comment by Yadnyawalkya** [comment]
Checked timer for negative as well as positive behaviors on three locations - 
1. On progress bar (of plan in process tab)
![screenshot from 2018-05-18 03-03-07](https://user-images.githubusercontent.com/10824880/40204988-082b00c2-5a48-11e8-94d8-bdba8979e92f.png)

2. On list view (of plans completed tab)
![screenshot from 2018-05-18 03-03-44](https://user-images.githubusercontent.com/10824880/40205011-1cb4378e-5a48-11e8-91a5-a1f87a3b2b2a.png)

3. On planing details page 
![screenshot from 2018-05-18 03-04-08](https://user-images.githubusercontent.com/10824880/40205021-2765b9e6-5a48-11e8-9993-5ea51f359b4b.png)

When you migrate two vms - 
1. If 1 fails and 1 is in process, timer1 stops for failed one and timer2 proceeds with ongoing vm's count
2. If both vms fails to migrate, timer stops for both after migration
3. If both vms successfully migrated, timer stops for both after migration
4. `Migration completed tab` shows maximum time among all vms migrated/failed in listview

All behaviors working as expected.

**Need changes** 
Auto-refresh requires for planing details page, progress bar already have that.
(Found, simplest way to know time without page refresh is to change paginator row count)

@priley86  @AparnaKarve: Is there any fixed refresh-time for this? found it is showing 5-10s on listview page.

**Comment by kedark3** [comment]
@mturley I think @Yadnyawalkya  has mentioned "Need Changes" in above comment, is what you are trying to work on. Auto-refresh the details page timer, progress bar, and last message from migration, etc. 

If you still need help ping me and we can get on Bluejeans where I can demo you current situation and let you know expected results.

**Comment by priley86** [comment]
hey guys - just wanted to add, this fix was merged into `master` branch yesterday to prep for the repo transfer to MIQ (planning to attempt this today). Unfortunately it looks like nightly is still pointed at `alpha` branch - so you won't see the updates on your end yes. We were planning to move the nightly build to point at `master` (in this [PR](https://github.com/ManageIQ/manageiq/pull/17432)) but we'd need to change it again to move to upstream MIQ anyways after the transfer. So hopefully we can get that resolved today and you can get these changes in nightly!

**Comment by priley86** [comment]
also...this issue is separate from #312...

**Comment by kedark3** [comment]
@priley86 agreed. We should keep those two separate. sorry for confusion. We should close this issue as the Elapsed time is already fixed. Auto-refresh will be addressed in #311 we can continue discussion there.

**Comment by priley86** [comment]
ok thanks for the clarification!
