### ISSUE TITLE
Delete an Infrastructure Mapping

### ISSUE THREAD

**Issue by serenamarie125** [priley86/miq_v2v_ui_plugin#317]
User should be able to delete an infrastructure mapping.  Add a delete action from the kebab menu for each infrastructure mapping.

1. If Infrastructure Mapping is associated with a Plan in Progress
     - The delete action should be disabled
1. If Infrastructure Mapping is associated with a Plan which has not yet been run
     - The delete action should be enabled
     - Show a delete confirmation dialog with "Cancel" and "Delete" buttons.  
     - Title: Delete Confirmation
     - Additional Text: 
1. If Infrastructure Mapping is associated with a Plan which has already been run
     - The delete action should be enabled
     - @vconzola do we still want to show a delete confirmation, but just make the message less strong?

**Comment by mturley** [comment]
Planning to assign myself here later today if none of you guys beat me to it.

**Comment by serenamarie125** [comment]
Duplicate of #297
