### ISSUE TITLE
"Download in Progress" shown in all rows even though I clicked download logs for only one VM

### ISSUE THREAD

**Issue by kedark3** [priley86/miq_v2v_ui_plugin#318]
![peek 2018-05-16 10-11](https://user-images.githubusercontent.com/8180469/40122354-99b34bf6-58f1-11e8-862e-7059344a0e3e.gif)

**Comment by AparnaKarve** [comment]
Will be fixed by https://github.com/priley86/miq_v2v_ui_plugin/pull/320

**Comment by kedark3** [comment]
@priley86  is this supposed to be in the nightly yet?
