### ISSUE TITLE
Wire Plan Wizard APIs into "real" APIs

### ISSUE THREAD

**Issue by priley86** [priley86/miq_v2v_ui_plugin#79]
* test the responses for `/api/service_templates` (to create a migration plan) and `/api/provision_requests` to create a Migration Request 
* change mock/dummy urls and remove the action creator exception responses (returning stubs now)

**Comment by mturley** [comment]
This one is now part of @AparnaKarve's latest PR https://github.com/priley86/miq_v2v_ui_plugin/pull/93, which I have been discussing with her.
