### ISSUE TITLE
Don't allow datastore mapping if the space available in the target datastore is less than the size of the selected source datastores

### ISSUE THREAD

**Issue by mturley** [priley86/miq_v2v_ui_plugin#98]
From @vconzola:

> Don't allow datastore mapping if the space available in the target datastore is less than the size of the selected source datastores. Show an inline error on target selection (preferred) or when user selects the Add Mapping button.

**Comment by vconzola** [comment]
Mockup:
![5b-createmapping-datastores w_ inline error](https://user-images.githubusercontent.com/22823035/36915409-8ab3e0ce-1e1e-11e8-87fb-dfe1266cd29e.png)

**Comment by serenamarie125** [comment]
@vconzola how would you suggest this work?  When the user clicks Add Mapping, it posts an Inline Notification, and nothing is adding in the tree below?

I'm not sure I like the inline notification, because it will move everything down in the wizard.  Would you be ok with an error dialog/modal?

**Comment by michaelkro** [comment]
I've started some work on this, so I'll post some gifs/screenshots to see what you guys think

**Comment by michaelkro** [comment]
## Case 1
* Source datastore(s) selected first
* Selected target datastore does not have enough capacity

## Gif
![1](https://user-images.githubusercontent.com/15141412/36968019-57c53f24-202f-11e8-82be-9a70de6f7fc3.gif)

## Screenshot
<img width="1920" alt="fullscreen_3_5_18__4_40_am" src="https://user-images.githubusercontent.com/15141412/36968113-925f5dc2-202f-11e8-828c-0445e02dbbcd.png">

**Comment by michaelkro** [comment]
## Case 2
* Valid selection of source and target datastores has already been made
* User attempts to add another source datastore that is too large

### gif
![2](https://user-images.githubusercontent.com/15141412/36968616-0dbab678-2031-11e8-8ee0-a51aa1c5ed78.gif)

**Comment by michaelkro** [comment]
## Case 3

* Valid selection of source and target datastores has already been made
* User cannot change to a target datastore that is too small
* If a valid selection is made, automatically dismiss alert

### gif
![3](https://user-images.githubusercontent.com/15141412/36969055-69c0dc80-2032-11e8-9d44-da17532eb3f4.gif)

**Comment by michaelkro** [comment]
## Case 4
* Target datastore selected first
* User cannot select source datastore(s) that exceed the target datastore's capacity
* Valid selection automatically dismisses alert

### gif
![4](https://user-images.githubusercontent.com/15141412/36969265-02f01cd6-2033-11e8-9bee-d51b36ed3b54.gif)

### Screenshot
<img width="1920" alt="fullscreen_3_5_18__5_04_am" src="https://user-images.githubusercontent.com/15141412/36969276-096d9d22-2033-11e8-9028-5f0a88575510.png">

**Comment by vconzola** [comment]
@MikeRo This is exactly how I pictured this working. Nice job. I suggest
using the message text in Case 4 for all cases.

Thanks.

VINCE CONZOLA

SR. INTERACTION DESIGNER, USER EXPERIENCE DESIGN

Red Hat <https://www.redhat.com/>

vconzola@redhat.com    T: 9197165041
<https://red.ht/sig>

**Comment by michaelkro** [comment]
The work shown above is complete, but depends on https://github.com/priley86/miq_v2v_ui_plugin/pull/108 being merged

**Comment by mturley** [comment]
Closed by #108
