### ISSUE TITLE
Remove the message "At least one VM needs to be selected." that appears before a CSV file has been imported in step 2 of the plans wizard

### ISSUE THREAD

**Issue by mturley** [priley86/miq_v2v_ui_plugin#99]
![atleastonevm](https://user-images.githubusercontent.com/811963/36997603-2c370604-2088-11e8-807c-2c80ebf02895.png)

**Comment by mturley** [comment]
Unassigned myself because it's not p1 and i didn't start yet.

**Comment by serenamarie125** [comment]
@mturley Can you include a screenshot in the description please?

**Comment by priley86** [comment]
@mturley do you want to tackle this one?

**Comment by mturley** [comment]
Sure, sorry for the delay reviewing / getting my env back up. Pushing a fix to my other PR, and then I'll do this one. @serenamarie125 i'll add that screenshot in a sec.

**Comment by priley86** [comment]
fixed in #117 - thanks @mturley !
